#!/usr/bin/env python

'''
    experientiarum
    
    ~ a place where I can leave my experiences
    
    @todo: dev/prod configs
    @todo: explicitly define which apps are on/off
    @todo: logging
    @todo: email
    
'''

from flask import Flask
from flaskext.mongokit import MongoKit


def generate_app(config):
    ## Define the application object
    app = Flask(__name__)
    
    app.config.from_object(config)
    
    db = MongoKit(__name__)

    ## Register Blueprints
    # BLOG
    from blog import blog
    app.register_blueprint(blog, prefix = '/blog')
    
    '''
    # BOOKMARKS
    from bookmarks import bookmarks
    app.register_blueprint(bookmarks, prefix = '/bookmarks')
    
    # PASTEBIN
    from pastebin import pastebin
    app.register_blueprint(pastebin, prefix = '/pastebin')
    
    # READLATERS
    from readlaters import readlaters
    app.register_blueprint(readlaters, prefix = '/readlaters')
    
    # TODO
    from todo import todo
    app.register_blueprint(todo, prefix = '/todo')
    '''
    
    ## Connect to Database
    connection = db.connect(app.config['MONGODB_HOST']
                            ,app.config['MONGODB_PORT'])

    return app